### PR TITLE
Merge Dev into main

### PR DESCRIPTION
**Pull request by fatahillah2606**

### CODE REVIEW

**Review by FadelKahfi — APPROVED** [review]
Fire project! 🔥

**Comment by galangsktwn** [comment]
😍😍🔥🔥🔥🔥

**Review by galangsktwn — COMMENTED** [review]
😍😍😍🔥🔥🔥🔥

**Review by galangsktwn — APPROVED** [review]
😍😍😍🔥🔥🔥🔥

**Pull request merged**
